**[Python Course Home Page](https://www.kaggle.com/learn/python)**

---

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
def compute_distances_no_loops(X, X_train):
    dists = -2 * np.dot(X, X_train.T) + np.sum(X_train**2,    axis=1) + np.sum(X**2, axis=1)[:, np.newaxis]
    return dists

In [28]:
X = np.array([[1, 2, 3], [2, 3, 5]])
X_train = np.array([1, 2, 3])

print('X.shape is', X.shape, 'X_train.shape is', X_train.shape)
# results = compute_distances_no_loops(X, X_train)

print(X-X_train)

np.linalg.norm(X-X_train, axis=1, ord=2), np.sqrt(6)

result = np.linalg.norm(X-X_train, axis=1, ord=2)
print(result==result.min())

# results
# from numpy.linalg import norm
# norm(X-(X_train[:, np.newaxis]), axis=0, ord=2)

X.shape is (2, 3) X_train.shape is (3,)
[[0 0 0]
 [1 1 2]]
[ True False]


In [ ]:
lst = [(1160, 7792), (693,2375), (369,961), 
       (301,871), (311,802), (218,656), (221,521)]
fork_num_lst = list(map(lambda x: x[1], lst))
print(fork_num_lst)

# fig = plt.figure(1) 

# #figure对象的add_axes()可以在其中创建一个axes对象,
# # add_axes()的参数为一个形如[left, bottom, width, height]的列表,取值范围在0与1之间;
# ax = fig.add_axes([0.1, 0.5, 0.8, 0.5]) # 我们把它放在了figure图形的上半部分，对应参数分别为：left, bottom, width, height;
# ax.set_xlabel('time')     #用axes对象的set_xlabel函数来设置它的xlabel

# line =ax.plot(range(5))[0]  #用axes对象的plot()进行绘图,它返回一个Line2D的对象;
# line.set_color('r')             # 再调用Line2D的对象的set_color函数设置color的属性;
# plt.show()

plt.plot(fork_num_lst)
plt.show()

In [39]:
df = pd.DataFrame([('bird', 389.0),
                   ('bird', 24.0),
                   ('mammal', 80.5),
                   ('mammal', np.nan)],
                   index=['falcon', 'parrot', 'lion', 'monkey'],
                   columns=('class', 'max_speed'))

# >>> df
#          class  max_speed
# falcon    bird      389.0
# parrot    bird       24.0
# lion    mammal       80.5
# monkey  mammal        NaN
df['aaa'] = [4, 5, 6, 8]

df

class  max_speed  aaa
falcon    bird      389.0    4
parrot    bird       24.0    5
lion    mammal       80.5    6
monkey  mammal        NaN    8

In [37]:
# df.reset_index(name='new_col')

# (df.groupby('class')
#           .size()
#           .reset_index(name='transactions_count'))

x = np.arange(6).reshape((2,3))

x = np.array([[0, -100], [30, 22], [11, 44]])

print('x is', x)
np.ptp(x, axis=1)

x is [[   0 -100]
 [  30   22]
 [  11   44]]


array([100,   8,  33])

In [30]:
x = np.array([1,2,3,4,5,6], np.float64)
print(x)
print('dytpe', x.dtype)
print('shape', x.shape)
print('strides', x.strides)

[1. 2. 3. 4. 5. 6.]
dytpe float64
shape (6,)
strides (8,)


In [3]:
a = 3
b = 4
c = 5
for val in [a, b, c]:
    val /= 5.0
print(a, b, c)

3 4 5


In [51]:
def is_prime_num(num):
    import math
    for i in range(2, int(math.sqrt(num))):
        if num%i==0:
            print('i is ', i)
            return False
    return True

for num in range(100000, 200000, 1):
    if is_prime_num(num):
        print('num is ', num)
        break
        
is_prime_num(10007)

i is  2
i is  11
i is  2
num is  100003


True

> You may have seen code that does this with certain popular libraries like Pandas, Numpy, Tensorflow, or Matplotlib. For example, it's a common convention to `import numpy as np` and `import pandas as pd`.

<hr/>

## 1.

Complete the code below. In case it's helpful, here is the table of available arithmatic operations:



| Operator     | Name           | Description                                            |
|--------------|----------------|--------------------------------------------------------|
| ``a + b``    | Addition       | Sum of ``a`` and ``b``                                 |
| ``a - b``    | Subtraction    | Difference of ``a`` and ``b``                          |
| ``a * b``    | Multiplication | Product of ``a`` and ``b``                             |
| ``a / b``    | True division  | Quotient of ``a`` and ``b``                            |
| ``a // b``   | Floor division | Quotient of ``a`` and ``b``, removing fractional parts |
| ``a % b``    | Modulus        | Integer remainder after division of ``a`` by ``b``     |
| ``a ** b``   | Exponentiation | ``a`` raised to the power of ``b``                     |
| ``-a``       | Negation       | The negative of ``a``                                  |

<span style="display:none"></span>


## Comparison Operations


| Operation     | Description                       || Operation     | Description                          |
|---------------|-----------------------------------||---------------|--------------------------------------|
| ``a == b``    | ``a`` equal to ``b``              || ``a != b``    | ``a`` not equal to ``b``             |
| ``a < b``     | ``a`` less than ``b``             || ``a > b``     | ``a`` greater than ``b``             |
| ``a <= b``    | ``a`` less than or equal to ``b`` || ``a >= b``    | ``a`` greater than or equal to ``b`` |

What a silly question. Of course it's an error. 

But what about...

(Click the "output" button to see the answer)

Python has precedence rules that determine the order in which operations get evaluated in expressions like above. For example, `and` has a higher precedence than `or`, which is why the first expression above is `True`. If we had evaluated it from left to right, we would have calculated `True or True` first (which is `True`), and then taken the `and` of that result with `False`, giving a final value of `False`.

You could try to [memorize the order of precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence), but a safer bet is to just use liberal parentheses. Not only does this help prevent bugs, it makes your intentions clearer to anyone who reads your code. 

For example, consider the following expression:

```python
prepared_for_weather = have_umbrella or rain_level < 5 and have_hood or not rain_level > 0 and is_workday
```

I'm trying to say that I'm safe from today's weather....
- if I have an umbrella...
- or if the rain isn't too heavy and I have a hood...
- otherwise, I'm still fine unless it's raining *and* it's a workday

But not only is my Python code hard to read, it has a bug. We can address both problems by adding some parentheses:

```python
for i in range(100):
    sum += i
    print(sum)
prepared_for_weather = have_umbrella or (rain_level < 5 and have_hood) or not (rain_level > 0 and is_workday)
```

You can add even more parentheses if you think it helps readability:

```python
prepared_for_weather = have_umbrella or ((rain_level < 5) and have_hood) or (not (rain_level > 0 and is_workday))
```

We can also split it over multiple lines to emphasize the 3-part structure described above:

```python
prepared_for_weather = (
    have_umbrella 
    or ((rain_level < 5) and have_hood) 
    or (not (rain_level > 0 and is_workday))
)
```